Reservation/config/routes.rb
Rails.application.routes.draw do
  # get 'auths/new'
  # get 'auths/create'
  # get 'auths/destroy'
  resource :auths, only: %i[new create destroy]
  resources :users
  resources :orders
  root to: 'rooms#index'
  get 'top/index'
  resources :rooms do
    resources :entries, only: %i[new create destroy index], shallow: true
  end
  post 'entries/confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Reservation/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :room
  belongs_to :user

  scope :least_entries,->(base_date) {
    where("reserved_date >= ? and reserved_date <= ?",
    base_date.to_date - 7.days, base_date.to_date + 7.days )
  }

  validates :user_id, :reserved_date, :usage_time, presence: true
end

Reservation/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: :destroy

  def new
    @entry = Entry.new(room_id: params[:room_id], user_id: current_user.id)
  end

  def index
    @entries = Entry.all
  end

  def create
    @entry = Entry.new(entry_params)

    if params[:back]
      render :new
      return
    end
    if @entry.save
      redirect_to room_path(@entry.room), notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  def destroy
    if current_user.id != @entry.user.id
      return redirect_to room_path(@entry.room), notice: 'You are not authorized to access this page.'
    end
    @entry.destroy

    head :no_content
  end

  def confirm
    @entry = Entry.new(entry_params)
    @entry.valid?
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:reserved_date, :usage_time, :room_id, :people, :user_id)
  end
end

Reservation/app/views/entries/_form.html.erb
<%= form_with(model: @entry, local: true, url: entries_confirm_path) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reserved_date %>
    <%= form.datetime_field :reserved_date %>
  </div>

  <div class="field">
    <%= form.label :usage_time %>
    <%= form.text_field :usage_time %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people %>
  </div>

  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :room_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Reservation/app/views/entries/confirm.html.erb
<p id="notice"><%= notice %></p>

  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <strong>Reserved_date:</strong>
  <%= @entry.reserved_date %>
</p>

<p>
  <strong>Usage_time:</strong>
  <%= @entry.usage_time %>
</p>

<p>
  <strong>People:</strong>
  <%= @entry.people %>
</p>

<%= form_with(model: @entry, local: true, url: room_entries_path(@entry.room_id)) do |form| %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :reserved_date %>
  <%= form.hidden_field :usage_time %>
  <%= form.hidden_field :people %>
  <%= form.hidden_field :room_id %>
  <%= form.submit %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

Reservation/app/views/entries/index.html.erb
<h1>予約トップページ</h1>
<p><%= "==<'会議室予約へようこそ'>==" %></p>
<p><%= raw "==<'希望の場所から会議室を選択できます！'>==" %></p>

Reservation/app/views/entries/new.html.erb
<h1>New Entries</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', room_entries_path %>