Reservation/config/routes.rb
Rails.application.routes.draw do
  # get 'auths/new'
  # get 'auths/create'
  # get 'auths/destroy'
  resource :auths, only: %i[new create destroy]
  resources :users
  resources :orders
  root to: 'rooms#index'
  get 'top/index'
  resources :rooms do
    resources :entries, only: %i[new create destroy index], shallow: true
  end
  post 'entries/confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Reservation/app/models/room.rb
class Room < ApplicationRecord
  has_many :entries
  has_many_attached :images, dependent: :destroy

  before_validation :remove_space
  validates :name,
    presence: { message: "会議名の入力は必須です" },
    length: { maximum: 30, message: "会議名は30文字以内で入力してください" },
    format: { with: /.*#\d{2}\z/, message: "会議名は「#数字」で終わる必要があります" }
  validates :place,
    presence: true,
    inclusion: [ "東京", "大阪", "福岡", "札幌", "仙台", "名古屋", "金沢" ]
  validates :number,
    presence: true,
    numericality: { greater_than_or_equal_to: 5, less_than_or_equal_to: 30 }
  validate :number_multiple_of_5

  private
  def number_multiple_of_5
    unless self.number % 5 == 0
      errors.add(:number, "は5の倍数で入力してください")
    end
  end

  def remove_space
    self.name.strip.gsub(/[ |　]+/, "_")
  end
end

Reservation/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :redirect_to_root_if_not_admin, only: %i[ new create edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.with_attached_images
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @entries = @room.entries
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        session[:room] = @room.name
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :place, :number, images: [])
    end

    def redirect_to_root_if_not_admin
      if current_user.admin == false
        return redirect_to root_path, notice: 'You are not authorized to access this page.'
      end
    end
end

Reservation/app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Reservation/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

Reservation/app/views/rooms/index.html.erb
<%= "最近登録の部屋、#{session[:room]}です。" if session[:room] %>
<p id="notice"><%= notice %></p>

<h1>予約管理のページへようこそ</h1>
<p>本日のアクセス時間: <%= Time.now.strftime("%Y年%m月%d日%H時%M分") %></p>

<table>
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.room.name' %></th>
      <th>Place</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.place %></td>
        <td><%= room.number %></td>
        <td><%= link_to 'Show', room %></td>
        <% if current_user.admin %>
          <td><%= link_to 'Edit', edit_room_path(room) %></td>
          <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path, class:"new-button" %>

Reservation/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

Reservation/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @room.place %>
</p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<p>
  <strong>Images:</strong>
  <% @room.images.each do |image|  %>
    <%= image_tag image, class: "image" %>
  <% end %>
</p>

<p>予約一覧</p>
<table>
  <tr>
    <th>予約者</th>
    <th>メールアドレス</th>
    <th>予約日</th>
  </tr>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.user.name %></td>
      <td><%= entry.user.email %></td>
      <td><%= entry.reserved_date %></td>
      <td>
        <% if current_user.email == entry.user.email %>
          <%= link_to '予約解除', entry_path(entry), remote: true, method: :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'New', new_room_entry_path(room_id: @room.id) %>
<% if current_user.admin %>
  <%= link_to 'Edit', edit_room_path(@room) %>
<% end %>
<%= link_to 'Back', rooms_path %>